Update jekyll-gh-pages.yml

diff --git a/.github/workflows/jekyll-gh-pages.yml b/.github/workflows/jekyll-gh-pages.yml
--- a/.github/workflows/jekyll-gh-pages.yml
+++ b/.github/workflows/jekyll-gh-pages.yml
@@ -47,6 +47,11 @@ jobs:
           echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
           echo "always-auth = true" >>  ~/.npmrc
 
+      - name: Who Am I
+        run: |
+          cat ~/.npmrc || echo ".npmrc file is missing"
+          npm whoami
+
       - name: Doctor
         run: npm doctor
 
